server:
  port: 8085
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/Desktop/test01
    username: sa
    password:
    driverClassName: org.h2.Driver  jpa:    hibernate:      ddl-auto: create-drop